/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DISTRIBUTED_PIPE_H_RPCGEN
#define _DISTRIBUTED_PIPE_H_RPCGEN

#include <rpc/rpc.h>
#include <unistd.h>

#ifdef __cplusplus
extern "C" {
#endif


#define RP 0x20000004
#define V1 17

#if defined(__STDC__) || defined(__cplusplus)
extern CLIENT * rp_17(char *host, int port);
#define write 231
extern  int * write_17(char **, CLIENT *);
extern  int * write_17_svc(char **, struct svc_req *);
#define read 232
extern  char ** read_17(void *, CLIENT *);
extern  char ** read_17_svc(void *, struct svc_req *);
#define ping 233
extern  int * ping_17(void *, CLIENT *);
extern  int * ping_17_svc(void *, struct svc_req *);
#define replicate_write 234
extern  int * replicate_write_17(char **, CLIENT *);
extern  int * replicate_write_17_svc(char **, struct svc_req *);
#define replicate_read 235
extern  int * replicate_read_17(void *, CLIENT *);
extern  int * replicate_read_17_svc(void *, struct svc_req *);
extern int rp_17_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern CLIENT * rp_17();
#define write 231
extern  int * write_17();
extern  int * write_17_svc();
#define read 232
extern  char ** read_17();
extern  char ** read_17_svc();
#define ping 233
extern int * ping_17();
extern int * ping_17_svc();
#define replicate_write 234
extern  int * replicate_write_17();
extern  int * replicate_write_17_svc();
#define replicate_read 235
extern  int * replicate_read_17();
extern  int * replicate_read_17_svc();
extern int rp_17_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DISTRIBUTED_PIPE_H_RPCGEN */
