/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "distributed_pipe.h"

#define BUFSIZE 512

int
main (int argc, char *argv[])
{
	char *host;
	int port;
	char *command;
	char writeCmd[] = "write";
	char readCmd[] = "read";
	int  *result_1;
	char * *result_2;
	char * write_17_arg;
	char *read_17_arg;
	char *ping_17_arg;

	if (argc < 4) {
		printf ("usage: %s server_host server_port command\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	port = atoi(argv[2]);
	command = argv[3];
	
	CLIENT *clnt = rp_17 (host, port);
	
	if (strcmp(writeCmd, command) == 0) {
		result_1 = ping_17(&ping_17_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
			exit(1);
		}
		write_17_arg = malloc(BUFSIZE);
		while (1) {
			printf("> ");
			fgets(write_17_arg, BUFSIZE, stdin);
			while (1) {
				result_1 = write_17(&write_17_arg, clnt);
				if (result_1 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
					exit(1);
				} else if (*result_1 != 0) {
					sleep(5);
				} else {
					break;
				}
			}
		}
		free(write_17_arg);
	} else if (strcmp(readCmd, command) == 0) {
		while (1) {
			result_2 = read_17((void*)&read_17_arg, clnt);
			if (result_2 == (char **) NULL) {
				result_1 = ping_17(&ping_17_arg, clnt);
				if (result_1 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
					exit(1);
				}
				sleep(5);
			} else {
				printf("%s", *result_2);
			}
		}
	} else {
		printf("Unknown command\n");
	}
	
	clnt_destroy (clnt);
	
	exit (0);
}
